### ISSUE TITLE
Nested Navigators

### ISSUE THREAD

**Issue by cek-cek** [mono0926/adaptive_dialog#1]
Hi!
I have a tabbed setup that use nested Navigators. It seems that the dialogs are displayed using the root navigator, because when the `void pop(T key) => Navigator.of(context).pop(key);` is executed in `showAlertDialog<T>` after pressing any dialog's action button, the tab's page is popped but the dialog stays on the screen.

I was able to successfully fix the issue by forcing to pop using root navigator, so that the dialog is actually removed off the screen after pressing an action button:
`  void pop(T key) => Navigator.of(context, rootNavigator: true).pop(key);`

Would you be so kind to extend your API to support this scenario? Thank you in advance, I love your work.

**Comment by mono0926** [comment]
Thanks, I’ll add that option in a few days 👍

**Comment by mono0926** [comment]
@cek-cek 

I've supported this and released as [0.4.0](https://pub.dev/packages/adaptive_dialog#040).

Could you try it?
And if the problem fixed, close the issue please 🐶

**Comment by cek-cek** [comment]
Works flawlessly out-of-the-box, thank you very much! 💖
