### ISSUE TITLE
Where "Label text" in "Supporting text" for Android Material Design 3

### ISSUE THREAD

**Issue by gorkovv** [mono0926/adaptive_dialog#108]
Please tell me how to set "Label text" in "Supporting text" for TextFormField()?
![Снимок экрана от 2023-05-03 14-56-52](https://user-images.githubusercontent.com/7299332/235863425-023f665f-e161-481a-9153-a45202279318.png)
You ignored it in class **DialogTextField**. And these properties are present in Material Design 3.
They just need to be added to **DialogTextField()** and transferred to **TextFormField->InputDecoration**.

**Comment by mono0926** [comment]
This package doesn't support that kind of flexibility as described here: https://github.com/mono0926/adaptive_dialog/issues/19#issuecomment-754476937

Material style TextField only feature is inconvenient for adaptive support.

So if you want to achieve it, implement it yourself without using this package.
