### ISSUE TITLE
Don't use 'BuildContext's across async gaps.

### ISSUE THREAD

**Issue by wangjunjx8868** [mono0926/adaptive_dialog#109]
Don't use 'BuildContext's across async gaps  in  void initState() event,

Try rewriting the code to not reference the 'BuildContext'.

how solve it?

**Comment by mono0926** [comment]
This is not related to this package.
You seems to be asking how to use [showDialog function - material library - Dart API](https://api.flutter.dev/flutter/material/showDialog.html) etc.
Please ask at https://stackoverflow.com or somewhere.
