### ISSUE TITLE
Dependency update needed imminently

### ISSUE THREAD

**Issue by fennelhans** [mono0926/adaptive_dialog#110]
Just a heads up that when the next version of Flutter drops (tomorrow), this package will start breaking.

The cause is due to the out-of-date dependency on macos_ui. I've submitted a bug report here:
https://github.com/macosui/macos_ui/issues/423

Once that issue is resolved, you'll need to update to whatever version they cook up.

**Comment by mono0926** [comment]
I'm considering to release `1.9.0-no_macos.0` or something which removes macos_ui dependency temporarily and show same UI as iOS instead 🤔

**Comment by mono0926** [comment]
@fennelhans 

Thanks for the report 👍 

Prerelease v1.9 is released and the issue is fixed:
https://pub.dev/packages/adaptive_dialog/versions/1.9.0-no-macos.2

- Next step: #112 
- Notice: https://github.com/mono0926/adaptive_dialog/discussions/113

**Comment by fennelhans** [comment]
![cant-thankyou-enough](https://github.com/mono0926/adaptive_dialog/assets/98828887/933fa100-b6e7-45ae-b8bd-7ec8bdc330e4)
