### ISSUE TITLE
adaptive loading dialog?

### ISSUE THREAD

**Issue by kyeshmz** [mono0926/adaptive_dialog#116]
Hi, I was wondering if an adaptive loading dialog using `CupertinoActivityIndicator` and `CircularProgressIndicator`, or if it is outside this scope of this package

**Comment by kyeshmz** [comment]
Actually, I think this is something doable, just with `CircularProgressIndicator.adaptive` and a general adaptive dialog here #95

**Comment by mono0926** [comment]
> Hi, I was wondering if an adaptive loading dialog using CupertinoActivityIndicator and CircularProgressIndicator, or if it is outside this scope of this package

No, it is out of scope 🐶
