### ISSUE TITLE
Can't run on Android because of the dynamic_color dependenciy 

### ISSUE THREAD

**Issue by ben55j** [mono0926/adaptive_dialog#117]
Hello,

I am encountering difficulties running my Flutter project on Android due to an issue related to the dynamic_color dependency of the adaptive_dialog package. The project works fine on iOS, but I'm facing problems specifically on Android.

Here is the error message I receive on my console:
'''
Build file '/Users/benjaminazogui/.pub-cache/hosted/pub.dev/dynamic_color-1.6.5/android/build.gradle' line: 27

* What went wrong:
A problem occurred evaluating project ':dynamic_color'.
> No signature of method: build_4x5nree6l1kdi4oln0m8bs64e.android() is applicable for argument types: (build_4x5nree6l1kdi4oln0m8bs64e$_run_closure2) values: [build_4x5nree6l1kdi4oln0m8bs64e$_run_closure2@1b9a2602]
'''

Here is my Flutter doctor: 
'''
flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 13.3.1 22E772610a darwin-x64, locale fr-FR)
    ! Warning: `dart` on your path resolves to /usr/local/Cellar/dart/2.10.3/libexec/bin/dart,
      which is not inside your current Flutter SDK checkout at
      /Users/benjaminazogui/Developer/flutter. Consider adding
      /Users/benjaminazogui/Developer/flutter/bin to the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

'''

Any help would be much appreciated !
Thank you, 
Benjamin

**Comment by mono0926** [comment]
@ben55j 

Thanks.
Example is also broken, and fixed by https://github.com/mono0926/adaptive_dialog/pull/118.
Your project should be able to be fixed similarly.
