### ISSUE TITLE
showConfirmationDialog doesn't apply AlertDialogAction.textStyle

### ISSUE THREAD

**Issue by JCKodel** [mono0926/adaptive_dialog#119]
While showing a `showConfirmationDialog` and providing some `AlertDialogAction` to `actions` property, the `textStyle` is not applied (in Android or iOS styles).

Tried to copy textTheme from current theme (`Theme.of(context)`), tried `TextStyle(fontSize: 8, color: Colors.green)`, nothing works.

For Android, the options are always black/white and bold (my intent was to remove the bold)

**Comment by mirkancal** [comment]
I also couldn't figure out how to change colors. Expecting OK button to be iOS-blue, and cancel to be red. Both are green(my primary color)
<img width="298" alt="image" src="https://github.com/mono0926/adaptive_dialog/assets/26160059/1faa8c42-7931-405c-bf3e-57f87115622a">

**Comment by mono0926** [comment]
@mirkancal 

It is not related to this issue.

It follows your theme, and you can also change like this: https://github.com/mono0926/adaptive_dialog/blob/1b055f4202fb6416eece4f42bc446d5c915b4cbf/example/lib/pages/alert_page.dart#L127-L140

If after making those adjustments you still cannot achieve what you intend, I recommend that you use the following API etc. directly without this package:
[showCupertinoDialog function - cupertino library - Dart API](https://api.flutter.dev/flutter/cupertino/showCupertinoDialog.html)

**Comment by mirkancal** [comment]
@mono0926 thank you, makes sense. I didn't realize it was using cupertino theme.
