### ISSUE TITLE
Error: No named parameter with the name 'controlSize'

### ISSUE THREAD

**Issue by gorkovv** [mono0926/adaptive_dialog#121]
After upgrading to version: 1.9.0 

```
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/adaptive_dialog-1.9.0/lib/src/text_input_dialog/macos_text_input_dialog.dart:176:25: Error: No named parameter with the name 'controlSize'.
```

**Comment by mono0926** [comment]
Use latest version(2.0.0) of [macos_ui | Flutter Package](https://pub.dev/packages/macos_ui/changelog).
(Don't specify the version by `dependency_overrides`)

**Comment by gorkovv** [comment]
> Use latest version(2.0.0) of [macos_ui | Flutter Package](https://pub.dev/packages/macos_ui/changelog). (Don't specify the version by `dependency_overrides`)

Thank you!
