### ISSUE TITLE
Dialog without context

### ISSUE THREAD

**Issue by VinniciusJesus** [mono0926/adaptive_dialog#122]
What would be the best solution when you don't have the context? I get push notifications, and I need to display the dialog on some of them

**Comment by mono0926** [comment]
This is not related to this package.
You seems to be asking how to use [showDialog function - material library - Dart API](https://api.flutter.dev/flutter/material/showDialog.html) etc. without BuildContext.
Please ask at https://stackoverflow.com/ or somewhere.
