### ISSUE TITLE
The input text color same with backgound when use CupertinoTextInputDialog

### ISSUE THREAD

**Issue by dodatw** [mono0926/adaptive_dialog#13]
I found a issue that when I switch to dark mode.
The DialogTextField text color still black. 
We cannot see. the text because the color is same with background.

Is there any way to set DialogTextField text color?

**Comment by dodatw** [comment]
I am using MaterialApp, if I replace by CupertinoApp, this issue gone.
It look like theme issue,
Is it possible provide "style" in DialogTextField to replace theme setting ?

**Comment by mono0926** [comment]
As you can see that [example](https://github.com/mono0926/adaptive_dialog/tree/master/example) works fine, https://github.com/mono0926/flutter_mono_kit/blob/3164ca2967e60085678d7ad6a76255c775c6f071/lib/extensions/theme_data.dart#L33 is needed.

**Comment by dodatw** [comment]
Thank. it's work!
