### ISSUE TITLE
Can't control dialog color from theme 

### ISSUE THREAD

**Issue by mohadel92** [mono0926/adaptive_dialog#131]
My issue is with my dark mode the dialog appears with white background and white text
i don't know which properties in ThemeData is responsible about dialog material color
so if possible to provide me with the required field to be changed or add color field in the showDialog method ?

screenshot:
<a href="https://ibb.co/JH9pSLw"><img src="https://i.ibb.co/tD921fT/payment.jpg" alt="payment" border="0"></a>

**Comment by mono0926** [comment]
adaptive_dialog supports dark mode properly, so the problem is on your side.

Anyway, you can change color etc. like this:  https://github.com/mono0926/adaptive_dialog/blob/6551534569ef7dde5cf80e2b1fa8f3c364c14398/example/lib/pages/alert_page.dart#L127-L140

**Comment by mohadel92** [comment]
@mono0926
and how to change the background in my case it is white ?
i don't want you to add any new feature to the package
i want only to know which property in themedata is releated to the dialog
