### ISSUE TITLE
Error: Type 'PopInvokedWithResultCallback' not found.

### ISSUE THREAD

**Issue by chasonHgg** [mono0926/adaptive_dialog#139]
flutter: 3.4.3
version: 2.2.0
use:
showOkAlertDialog(
        context: context,
        title: "xxxx",
        message: "22222",
 );

error:

./../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/modal_action_sheet/modal_action_sheet.dart:27:3: Error: Type
'PopInvokedWithResultCallback' not found.
  PopInvokedWithResultCallback<T>? onPopInvokedWithResult,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/text_input_dialog/show_text_answer_dialog.dart:25:3: Error: Type
'PopInvokedWithResultCallback' not found.
  PopInvokedWithResultCallback<List<String>?>? onPopInvokedWithResult,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/text_input_dialog/show_text_input_dialog.dart:28:3: Error: Type
'PopInvokedWithResultCallback' not found.
  PopInvokedWithResultCallback<List<String>?>? onPopInvokedWithResult,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/alert_dialog/show_alert_dialog.dart:32:3: Error: Type 'PopInvokedWithResultCallback' not
found.
  PopInvokedWithResultCallback<T>? onPopInvokedWithResult,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
../../../.pub-cache/hosted/pub.dev/adaptive_dialog-2.2.0/lib/src/alert_dialog/show_confirmation_dialog.dart:36:3: Error: Type
'PopInvokedWithResultCallback' not found.
  PopInvokedWithResultCallback<T>? onPopInvokedWithResult,
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by mono0926** [comment]
Please take a look at this:
https://github.com/mono0926/adaptive_dialog/issues/135#issuecomment-2362637240
