### ISSUE TITLE
Default selection in showConfirmationDialog

### ISSUE THREAD

**Issue by xJon** [mono0926/adaptive_dialog#14]
Is it possible to have a default selected value in `showConfirmationDialog`?
I understand that `isDefaultAction` is not what I am talking about.
Thank you!

**Comment by mono0926** [comment]
Not supported but, `initialSelectedActionKey` was added at v0.9.3, so supported now 👌 

See: https://pub.dev/documentation/adaptive_dialog/latest/adaptive_dialog/showConfirmationDialog.html
