### ISSUE TITLE
i realy do not understand how to use it.

### ISSUE THREAD

**Issue by Hopheylalal** [mono0926/adaptive_dialog#16]
Why i get some second alert dialog after press OK?
How i can get text from showTextAnswerDialog ?
Somebody give me example please.

**Comment by mono0926** [comment]
Type "Flutter" as coded here:
https://github.com/mono0926/adaptive_dialog/blob/db57c7914b255a9e5daea46a32196be842e2bfb2/example/lib/pages/text_input_dialog_page.dart#L129

**Comment by Hopheylalal** [comment]
> adaptive_dialog/example/lib/pages/text_input_dialog_page.dart
Thank you but how i can handle ok and cancel buttons in showTextInputDialog? in future i get only text from textField
