### ISSUE TITLE
Help me please

### ISSUE THREAD

**Issue by Hopheylalal** [mono0926/adaptive_dialog#17]
I do not understand how i can handle OK and CANCEL buttons in showTextInputDialog. In future i get only text from textField.

and why i have this?

showTextInputDialog(
                                    context: context,
                                    textFields: [DialogTextField()],
                                    title: 'Создание папки',
                                    message: 'Введите название папки',
                                    okLabel: 'Создать',
                                    cancelLabel: 'Отмена',
                                  ).then((newFolder) {
                                    print(newFolder.isEmpty);  **----This is FALSE**
                                    print(newFolder); **---- and this get me [ ] - empty!**

**Comment by mono0926** [comment]
I cannot understand your problems.
