### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by Hopheylalal** [mono0926/adaptive_dialog#18]
i have showTextInputDialog()

but where i can past functions on OK and CANCEL buttons?

for example i expect some like this:

showTextInputDialog(
  onPressOKButton(){
      doSomeThing
  }
onPressCANCELButton(){
      doSomeThing
  }
)

How i can handle tap on OK and CANCEL buttons???

**Comment by mono0926** [comment]
No, you can’t.

**Comment by szwss** [comment]
那么请问,我如何获得输入框里面填的所有值呢?能否给个例子,谢谢

**Comment by mono0926** [comment]
@szwss 

https://github.com/mono0926/adaptive_dialog/blob/db57c7914b255a9e5daea46a32196be842e2bfb2/example/lib/pages/text_input_dialog_page.dart#L82

**Comment by szwss** [comment]
thank you
