### ISSUE TITLE
How could I change dialog text fontsize

### ISSUE THREAD

**Issue by JamesTaylor04** [mono0926/adaptive_dialog#19]

**Comment by Hopheylalal** [comment]
Do you know how i can Ok and CANCEL buttons handle? How i can do something when i press OK or CANCEL? 
owner of this package do not wont help me

**Comment by mono0926** [comment]
No, that kind of feature isn't supported.
This packages keeps usage and UI simple like iOS official alert dialog.

You had better to implement your own functions by using [showDialog](https://api.flutter.dev/flutter/material/showDialog.html) etc.

**Comment by bit-burger** [comment]
Just fork the project if you want it implemented shouldn't be that hard, done it like a hundred times
