### ISSUE TITLE
showTextInputDialog DialogTextField prefixText out of sight

### ISSUE THREAD

**Issue by szwss** [mono0926/adaptive_dialog#20]
This situation occurs when the focus is not on the input, and it can be seen when the focus is on the input

**Comment by mono0926** [comment]
@szwss 
Could you paste the sample code and screenshot?

**Comment by szwss** [comment]
I forgot to mention a condition. This will only happen when the content of the input box is empty. I have filled in the content by default here, so this problem is also solved. It should be easy for you to recreate this problem. Put the input library Delete the content in, remove the focus to find the problem

**Comment by mono0926** [comment]
As you ignored the cost for my request, I ignore your request.
