### ISSUE TITLE
Add support for macOS dialogs

### ISSUE THREAD

**Issue by nilsreichardt** [mono0926/adaptive_dialog#27]
- [x] #67 
- [x] #68

## Description
We deploy our app to Android, iOS, Web and macOS. It would be great to have the option to display on macOS the dialog with native design:

| Big Sur | Catalina |
| - | - |
|![image](https://user-images.githubusercontent.com/24459435/109727718-2087cd80-7bb5-11eb-8848-c3e12de7b998.png)| ![image](https://user-images.githubusercontent.com/24459435/109727767-372e2480-7bb5-11eb-9cca-aa5685815b99.png) |

https://github.com/GroovinChip/macos_ui#dialogs

**Comment by mono0926** [comment]
https://github.com/GroovinChip/macos_ui#dialogs looks good.

**Comment by cbenhagen** [comment]
https://pub.dev/packages/ndialog might also be an option

**Comment by SebAubin** [comment]
Hi, can we have an ETA on this? This would be a great for us. Thanks

**Comment by mono0926** [comment]
Released 🎉 
https://github.com/mono0926/adaptive_dialog/releases/tag/1.6.0

- Demo: https://mono0926.com/adaptive_dialog
