### ISSUE TITLE
Provide a way to override default theme

### ISSUE THREAD

**Issue by haashem** [mono0926/adaptive_dialog#28]
By default buttons use primary color. but I want use a different color, or secondary color. is there any plan to support this?
as you see from the below image, primary color is orange and reduces readability.

<img width="374" alt="Screen Shot 2021-03-12 at 15 05 45" src="https://user-images.githubusercontent.com/3206748/110933718-9115b380-8346-11eb-952b-4c67ed9b4f09.png">

**Comment by mono0926** [comment]
`builder` parameter has been added at #60, and released 1.5.0.

Examples:

- https://github.com/mono0926/adaptive_dialog/blob/3da2d5451276599baa03c50b253855ea9d296c80/example/lib/pages/alert_page.dart#L94
- https://github.com/mono0926/adaptive_dialog/blob/3da2d5451276599baa03c50b253855ea9d296c80/example/lib/pages/sheet_page.dart#L89
