### ISSUE TITLE
Modal Action Sheet is not scrollable on Android

### ISSUE THREAD

**Issue by ptrbrynt** [mono0926/adaptive_dialog#3]
# Steps to Reproduce

```dart
showModalActionSheet<int>(
  context: context,
  actions: List.generate(10, (i) {
    return SheetAction<int>(
      key: i,
      label: i.toString(),
    );
  }),
);
```

**Comment by mono0926** [comment]
@ptrbrynt 

This example's parameter will resolve the issue:

https://github.com/mono0926/adaptive_dialog/blob/b7f55f02583ff756e9ae35d4b0be9b74fae349a7/example/lib/pages/sheet_page.dart#L142-L143

https://github.com/mono0926/adaptive_dialog/blob/17b4764a52d9565951fed48fd24a2f3e66f4f46a/lib/src/modal_action_sheet/modal_action_sheet.dart#L59-L68

(Sorry for no documentation)

I'm considering handle this automatically 🤔
