### ISSUE TITLE
"showTextInputDialog" returns double the value in ios.

### ISSUE THREAD

**Issue by willyadinata** [mono0926/adaptive_dialog#31]
MyCode:

showTextInputDialog(
  context: context,
  title: 'Test Text Input Dialog',
  textFields: [
    DialogTextField(
      hintText: 'Input value',
      keyboardType: TextInputType.number,
      validator: (value) {
        if (value == null || value.isEmpty) {
          return 'Please enter number';
        }
        debugPrint('Value: $value');
        return null;
      },
    )
  ],
)

Screenshot terminal in iOS:
![Screen Shot 2021-04-06 at 11 15 52](https://user-images.githubusercontent.com/50712778/113658615-8c84b680-96ca-11eb-8fc1-2e3794a50600.png)

Screenshot terminal in Android:
![Screen Shot 2021-04-06 at 11 22 46](https://user-images.githubusercontent.com/50712778/113658645-99090f00-96ca-11eb-9526-e66e5cacae50.png)

**Comment by mono0926** [comment]
Could not reproduced.
https://github.com/mono0926/adaptive_dialog/blob/e71d6bb0e4459e2394d7c19c973a376e361fc3f5/example/lib/pages/text_input_dialog_page.dart#L23 and your code works without duplicated values.
