### ISSUE TITLE
disable "ok" when input text is empty on showTextInputDialog.

### ISSUE THREAD

**Issue by dodatw** [mono0926/adaptive_dialog#32]
I want to implement a feature like
"disable "ok" when input text is empty on showTextInputDialog"

is it support?

**Comment by mono0926** [comment]
Use `validator` like this example instead:

https://github.com/mono0926/adaptive_dialog/blob/e71d6bb0e4459e2394d7c19c973a376e361fc3f5/example/lib/pages/text_input_dialog_page.dart#L69

```dart
                    validator: (text) => text == null || text.isEmpty
                        ? 'Should not be empty'
                        : null,
```

<img width="384" alt="image" src="https://user-images.githubusercontent.com/1255062/118237888-bc498a00-b4d2-11eb-82cb-961f934366f3.png">

I think error messages are easier to understand than disabling a button.

I'd like to keep the API of this package as simple as possible.
This feature request exceeds that level, so if you want to achieve it, implement it yourself without using this package.

**Comment by dodatw** [comment]
Thanks, It works!
