### ISSUE TITLE
How to prevent physical return/back action?

### ISSUE THREAD

**Issue by chennyshan** [mono0926/adaptive_dialog#34]
Hi, thanks for your attention in advance.
Is there any param to prevent physical return/back action? Such as the back key on android device? The param 'barrierDismissible' can't satisfy my requirement.

**Comment by mono0926** [comment]
Added `onWillPop` paramter at https://pub.dev/packages/adaptive_dialog/changelog#100.

Here is an example:
https://github.com/mono0926/adaptive_dialog/blob/47f1de21ba743647e4e0ac6d14b6349004638285/example/lib/pages/alert_page.dart#L37
