### ISSUE TITLE
is it possible to show dialog without build context

### ISSUE THREAD

**Issue by mohadel92** [mono0926/adaptive_dialog#35]
HI,
i am looking forward to showing a dialog from inside a Getx Controller 
when a push notification been received,
i don't have a context in this situation
is it possible  show dialog without context

**Comment by mohadel92** [comment]
i found the solution is to pass Get.context as a parameter inside the showDialog function

**Comment by oleksii-pimenov** [comment]
> i found the solution is to pass Get.context as a parameter inside the showDialog function

in this case Get routing is mandatory, woun't work without it
