### ISSUE TITLE
DialogTextField set maxLines is not effect

### ISSUE THREAD

**Issue by jacobson-wu** [mono0926/adaptive_dialog#38]
It can be input more then 5 lines.

 final introductions = await showTextInputDialog(
      context: context,
      textFields: [
        DialogTextField(
          initialText: _userInfo.introduction,
          keyboardType: TextInputType.multiline,
          // minLines: 1,
          maxLines: 5,
        ),
      ],
      title: 'input introduction',
    );

**Comment by mono0926** [comment]
Confirmed it works without no problem on Android and iOS by changin https://github.com/mono0926/adaptive_dialog/blob/eeba060e57e4945754cbfd62a080eb305754a9bd/example/lib/pages/text_input_dialog_page.dart#L26 to this:

```dart
                textFields: const [
                  DialogTextField(
                    maxLines: 5,
                  ),
                ],
```

iOS | Android
--- | ---
![Screenshot_1625217003](https://user-images.githubusercontent.com/1255062/124251540-fe9d5800-db60-11eb-8f00-3fcb90f0a65d.png) | ![Screenshot_1625217015](https://user-images.githubusercontent.com/1255062/124251551-00ffb200-db61-11eb-8187-86c65e2e7c2f.png)
