### ISSUE TITLE
showTextAnswerDialog() - add optional arg to submit form when user hits enter on last input field

### ISSUE THREAD

**Issue by oysterpack** [mono0926/adaptive_dialog#39]
## Story
As a user, I would like the form to automatically submit when the user hits the enter button on the last text input field.

## Spec
Add an optional `bool autoSubmit = false` arg to `showTextAnswerDialog()` 
- it true, then when the text input field `onSubitted` action should auto-submit the form

**Comment by mono0926** [comment]
@oysterpack 

Thanks for the feedback.
Supported at 1.1.0: https://pub.dev/packages/adaptive_dialog/changelog#110
