### ISSUE TITLE
No background color in Modal Action Sheet Android

### ISSUE THREAD

**Issue by alpi2111** [mono0926/adaptive_dialog#4]
Hi, sorry for my english.

I have a issue when I use showModalActioSheet. In iOS looks good but in Android the background color it's transparent and I don't see the content. This is my code:

````
import 'package:adaptive_dialog/adaptive_dialog.dart' as adaptive;
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

Future<String> showOptionsBottomMenu({
  @required BuildContext context,
  String title = 'Opciones',
  String cancelLabel = 'Cancelar',
  String message,
}) async {
  return await adaptive.showModalActionSheet<String>(
    context: context,
    title: title,
    cancelLabel: cancelLabel,
    message: message,
    isDismissible: true,
    style: adaptive.AdaptiveStyle.material,
    actions: [
      const adaptive.SheetAction(
        label: 'Tomar Foto',
        icon: Icons.insert_photo,
        key: 'tomar',
      ),
      const adaptive.SheetAction(
        label: 'Seleccionar Fotos',
        icon: Icons.insert_photo,
        key: 'seleccionar',
      ),
      const adaptive.SheetAction(
        label: 'Seleccionar archivos pdf, word, excel, power point',
        icon: Icons.insert_photo,
        key: 'seleccionar_archivos',
      ),
    ],
  );
}
````

I'm using Flutter v1.17.3.

Here the screenshots:

1. iOS
![imagen](https://user-images.githubusercontent.com/44912302/84211753-b4db5e80-aa81-11ea-8eb0-1f1339c7dc2d.png)

2. Android
![imagen](https://user-images.githubusercontent.com/44912302/84211829-e6542a00-aa81-11ea-9f03-2dc106b1039b.png)

**Comment by mono0926** [comment]
@alpi2111 

This example works well, so it's the issue of your project(maybe theme):
https://github.com/mono0926/adaptive_dialog/blob/master/example/lib/pages/sheet_page.dart

By default, the background color of sheet is `canvasColor` of `ThemeData`.
You can also set `bottomSheetTheme`.
You seems to set `Colors.transparent` to either of them, and it causes the problem.

`adaptive_dialog` prioritizes simplicity, so I don't plan to add `backgroundColor` parameter to `showModalActionSheet`.

**Comment by alpi2111** [comment]
ok, thanks.
