### ISSUE TITLE
There is a problem on iOS

### ISSUE THREAD

**Issue by gkShine** [mono0926/adaptive_dialog#41]
![Simulator Screen Shot - iPhone 12 - 2021-07-22 at 15 59 07](https://user-images.githubusercontent.com/3202737/126607103-30eca55a-fa0e-4321-92eb-2e3b940af7fd.png)

**Comment by gkShine** [comment]
when i touch it,  the background color will change

**Comment by mono0926** [comment]
Not reproduced at example code.
