### ISSUE TITLE
Option to change cursorColor for showTextInputDialog()

### ISSUE THREAD

**Issue by StarBattle08** [mono0926/adaptive_dialog#42]
I use MaterialApp for my application and i can configure the cursorColor inside themeData, but it only affects android and not iOS

**Comment by mono0926** [comment]
`cursorColor` of CupertinoTextField follows `primaryColor` of ThemData.
CupertinoTextField accepts `cursorColor`, but `adaptive_dialog` doesn't support that kind of flexibility now.

### Related Issues

- #28

**Comment by mono0926** [comment]
`builder` parameter has been added at #60, and released as 1.5.0.

Examples:

- https://github.com/mono0926/adaptive_dialog/blob/3da2d5451276599baa03c50b253855ea9d296c80/example/lib/pages/alert_page.dart#L94
- https://github.com/mono0926/adaptive_dialog/blob/3da2d5451276599baa03c50b253855ea9d296c80/example/lib/pages/sheet_page.dart#L89
