### ISSUE TITLE
iOS dark mode text input is invisible

### ISSUE THREAD

**Issue by krillefear** [mono0926/adaptive_dialog#43]
Hello, I really love your package and use it in my app FluffyChat but I have seen that on iOS in dark mode the text is not visible in the `showTextInputDialog()`.

![Screenshot](https://gitlab.com/famedly/fluffychat/uploads/35d1e32d1c906501562adbe5343fb754/589474C3-4C8A-4022-9176-3FC617F8C28D.png)

**Comment by mono0926** [comment]
https://github.com/mono0926/adaptive_dialog#the-input-text-color-same-with-backgound-when-use-cupertinotextinputdialog should fix the problem 👌

**Comment by krillefear** [comment]
Thank you :-D
