### ISSUE TITLE
showConfirmationDialog height

### ISSUE THREAD

**Issue by xJon** [mono0926/adaptive_dialog#5]
Hi,
Is there any way while using `showConfirmationDialog` to have a more "responsive" height?
The widget works well when the list is long enough to be scrollable, and I am aware of `contentMaxHeight` which I am using currently, but it's not ideal.

Maybe you could add an option to pass to the widget's `ListView` a `shrinkWrap` value, so one could set it to `true`.

Thanks!

**Comment by mono0926** [comment]
@xJon 

Thanks for the feedback.
Your opinion is reasonable, so I added `shrinkWrap` to `showConfirmationDialog`, and released 0.7.4:
https://pub.dev/packages/adaptive_dialog#074

**Comment by xJon** [comment]
Thank you!

**Comment by mono0926** [comment]
>  Is it also possible to control the ListView's physics: NeverScrollableScrollPhysics(), to make it more usable for non-scrollable, shorter dialogs?

Supported at 0.7.5 👌 :
https://pub.dev/packages/adaptive_dialog#075
