### ISSUE TITLE
Android: Modal Action Sheet not scrollable

### ISSUE THREAD

**Issue by obrunsmann** [mono0926/adaptive_dialog#52]
When using a modal action sheet with many options it is well scrollable under iOS but not on Android. So the user can only select the first ~5 options.

**Comment by mono0926** [comment]
It can be scrollable by specifying this: https://github.com/mono0926/adaptive_dialog/blob/eeba060e57e4945754cbfd62a080eb305754a9bd/example/lib/pages/sheet_page.dart#L142
