### ISSUE TITLE
Option to change the directionality of text and text-direction-sensitive render objects

### ISSUE THREAD

**Issue by Aanu1995** [mono0926/adaptive_dialog#56]
In my app, I need to change the text direction of the title and the content in the dialog but I could not because there is no argument provided for text direction.

**Expected Behaviour**
The dialog should have support for text direction by making Directionality the root child of the dialog.

``` 
showModal(
      context: context,
      useRootNavigator: useRootNavigator,
      configuration: FadeScaleTransitionConfiguration(
        barrierDismissible: barrierDismissible,
      ),
      builder: (context) => Directionality(
        textDirection: TextDirection.rtl,
        child: WillPopScope(
          onWillPop: onWillPop,
          child: AlertDialog(
            title: titleText,
            content: messageText,
            actions: actions.convertToMaterialDialogActions(
              onPressed: pop,
              destructiveColor: colorScheme.error,
              fullyCapitalized: fullyCapitalizedForMaterial,
            ),
            actionsOverflowDirection: actionsOverflowDirection,
            scrollable: true,
          ),
        ),
      ),
    );
```

**Comment by mono0926** [comment]
@Aanu1995 

Why do you want to change the directionality only for some screens, such as dialogs?
If you'd like to change the whole app directionality, you can do it by adding the following to https://github.com/mono0926/adaptive_dialog/blob/eeba060e57e4945754cbfd62a080eb305754a9bd/example/lib/app.dart#L25, and the dialog of `adaptive_dialog` will follow it. Is that not enough?

```dart
      builder: (context, child) => Directionality(
        textDirection: TextDirection.rtl,
        child: child!,
      ),
```

**Comment by Aanu1995** [comment]
Thank you @mono0926 . I am actually aware of this and my app already handled that for Hebrew language. What I needed to do in the dialog was to enforce direction ltr instead of the global directionality because the text I intend to display is in English. Cases of changing direction for a particular screen or widget is possible and I believe it is the reason why the Flutter team added that support for widgets (e.g Text widget) in Flutter.
