### ISSUE TITLE
Possible to give showTextInputDialog default text?

### ISSUE THREAD

**Issue by mark8044** [mono0926/adaptive_dialog#74]
Is it possible to give `showTextInputDialog` some default text that could then be edited?  This would be different from hintText that would disappear once the user starts typing.

**Comment by mono0926** [comment]
Is https://github.com/mono0926/adaptive_dialog/blob/83088c27dc4206d3e156c38513452288ea4a493b/example/lib/pages/text_input_dialog_page.dart#L143 what you want?

**Comment by mark8044** [comment]
BINGO.  Thank you very much!
