### ISSUE TITLE
Widget not completely supporting dark theming

### ISSUE THREAD

**Issue by lcsvcn** [mono0926/adaptive_dialog#81]
<img src="https://user-images.githubusercontent.com/6011385/175109518-ae02efeb-7110-4454-bf07-87f15d7ddb7b.png" alt="screenshot" height="200">
<img src="https://user-images.githubusercontent.com/6011385/175109382-cfd853a3-93d6-4ed5-9b92-f52701c8fd93.png" alt="screenshot" height="200">
<img src="https://user-images.githubusercontent.com/6011385/175109454-cdd87b97-ecd1-4afc-89c0-92bd64eb208c.png" alt="screenshot" height="200">

Here is the code:
```
showTextInputDialog(
      title: "Write a comment",
      okLabel: "Send",
      cancelLabel: "Cancel",
      context: context,
      textFields: [
        DialogTextField(
          hintText: "comment",
        ),
      ],
    ).then((value) {
      if (value != null && value.isNotEmpty) {
        post.comment = value[0];
      }
howTextInputDialog(
      title: "Write a comment",
      okLabel: "Send",
      cancelLabel: "Cancel",
      context: context,
      textFields: [
        DialogTextField(
          hintText: "comment",
        ),
      ],
    ).then((value) {
        // do stuff
});
```

**Expected behaviour:** On dark theme, the inside text would be white to contract with input black background.

**Comment by mono0926** [comment]
https://github.com/mono0926/adaptive_dialog#the-input-text-color-same-with-backgound-when-using-cupertinotextinputdialog is needed.
