### ISSUE TITLE
showTextInputDialog() When you click OK, the size of the dialog box will change.

### ISSUE THREAD

**Issue by HeebeLee** [mono0926/adaptive_dialog#9]
But clicking on Cancel doesn't.

iOS13, iPhone 11

**Comment by mono0926** [comment]
`showTextInputDialog()` uses [showCupertinoDialog()](https://api.flutter.dev/flutter/cupertino/showCupertinoDialog.html), which is contained in Flutter framework, so this looks like Flutter's side problem.

And I don't understand the behavior, so I'd like to see the gif.

**Comment by andynvt** [comment]
same issue
