### ISSUE TITLE
How to change text color of DialogTextField?

### ISSUE THREAD

**Issue by rlfolden** [mono0926/adaptive_dialog#93]
Hello, 

Can you provide an example of how to change the DialogTextField colors using showTextInputDialog()??

I tried using the builder capability but have been unable to affect ANY change desired other than turning the dialog gray.

I'd like the dialog to be dark, with the DialogTextField to be black text on a white background.

Thank you.
R. Folden

**Comment by mono0926** [comment]
For material style, add below to https://github.com/mono0926/adaptive_dialog/blob/316147b7191a5316ea7f3da96d850651c60b2fd2/example/lib/pages/text_input_dialog_page.dart#L34.

```dart
                builder: (context, dialog) {
                  return Theme(
                    data: theme.copyWith(
                      textTheme: theme.textTheme.copyWith(
                        titleMedium: const TextStyle(color: Colors.red),
                      ),
                    ),
                    child: dialog,
                  );
                },
```

<img width="654" alt="image" src="https://user-images.githubusercontent.com/1255062/195776093-45f8ba6c-2d40-472a-814e-5f76b00bc357.png">

For other platforms, it can be done likewise.

**Comment by vgavrilovikj** [comment]
@mono0926 what exactly does "theme" reference in this line `data: theme.copyWith(`
