### ISSUE TITLE
How to prevent text in showOkCancelAlertDialog from being cut off?

### ISSUE THREAD

**Issue by jooy2** [mono0926/adaptive_dialog#96]
![image](https://user-images.githubusercontent.com/48266008/211735708-787cd3a9-7b12-43c8-92a8-34693625d9cd.png)

Hello,
If i use a long message in showOkCancelAlertDialog, the text is expressed in one line as shown in the picture above.
Is there a way to allow overflow and display text in multiple lines?

```dart
OkCancelResult select = await showOkCancelAlertDialog(
        context: context, message: 'HelloText1HelloText2HelloText3HelloText4');

if (select == OkCancelResult.ok) {
    // Do something
}
```

Regards,

**Comment by mono0926** [comment]
I can't reproduce it in my environment 🤔 

<img src="https://user-images.githubusercontent.com/1255062/211737335-9be96d30-bb34-480d-907b-a4fda79bcef0.png" width="320px" />

**Comment by jooy2** [comment]
@mono0926 Hello, thanks for the quick reply and sorry for the lack of information.

The environment I tried is based on Android's material.
I would like to know if this is a constraint set in the material design or can be solved programmatically.


Here is the full code:

```dart
import 'package:adaptive_dialog/adaptive_dialog.dart';
import 'package:flutter/material.dart';

class TestScreen extends StatefulWidget {
  const TestScreen({Key? key}) : super(key: key);

  @override
  State<TestScreen> createState() => TestScreenState();
}

class TestScreenState extends State<TestScreen> {
  @override
  void initState() {
    super.initState();
  }

  handleClickButton() async {
    OkCancelResult select = await showOkCancelAlertDialog(
        context: context, message: 'HelloText1HelloText2HelloText3HelloText4');
    if (select == OkCancelResult.ok) {
      // Do Something
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: <Widget>[
          OutlinedButton(
              onPressed: handleClickButton,
              style: TextButton.styleFrom(
                foregroundColor: Colors.black,
                backgroundColor: Colors.white,
                padding: EdgeInsets.zero,
                tapTargetSize: MaterialTapTargetSize.shrinkWrap,
                minimumSize: const Size(50, 38),
              ),
              child: const Text('Click to show dialog')),
        ],
      )),
    );
  }
}
```

**Comment by jooy2** [comment]
Full image:

![image](https://user-images.githubusercontent.com/48266008/211741506-bee98fde-2b3d-4e50-a0d6-e66ffe15a87d.png)

**Comment by mono0926** [comment]
@jooy2 

I can't reproduce it on my Android device, too 🤔

AlertDialog is used simply:
https://github.com/mono0926/adaptive_dialog/blob/e03d828a55442eac81f20363bc50beaef36d4b1e/lib/src/alert_dialog/show_alert_dialog.dart#L123-L135

I suspect that there is a problem in your environment (e.g. the Flutter SDK source code has been edited).

**Comment by jooy2** [comment]
@mono0926 Oops, my mistake... sorry for the confusion. As a result of checking, it was confirmed that it was caused by a specific TextStyle value defined in Global ThemeData.

Yes, that's right. It was a problem with my project code 🥲

In conclusion, this is not a problem, so I will close the issue. Thank you for your time.
And thanks for making such an awesome module!
