### ISSUE TITLE
How do I handle action after showOkCancelDialog?

### ISSUE THREAD

**Issue by jott8** [mono0926/adaptive_dialog#97]
Is there a function like onPressed to handle what happens after I pressed 'Ok' or 'Cancel'? I looked through the implementation, but can't figure it out.

**Comment by mono0926** [comment]
Check result [here](https://github.com/mono0926/adaptive_dialog/blob/e03d828a55442eac81f20363bc50beaef36d4b1e/example/lib/pages/alert_page.dart#L121).

If you have requirements that cannot be met by this, please implement your own.
This package is designed to be as simple as possible, with minimal detailed functionality.

**Comment by jott8** [comment]
But is it possible to do a specific action when 'Ok' gets pressed and another action when 'Cancel' gets pressed? I dont understand the result either

**Comment by CaelanBistro** [comment]
Hi @jott8,

I've included how I implemented the code below by using a switch statement after receiving the result.

` 

        // Create the alert dialog
        final result = await showOkCancelAlertDialog(context: context, title: "Do you like to dance?")
        // Handle the result of Alert Dialog
        switch (result) {
          case OkCancelResult.ok:
            await Provider().activeDanceMode();
            break;
          case OkCancelResult.cancel:
            break;
        }
`

**Comment by jott8** [comment]
Thank you, that's exactly what I was looking for. I didn't store the showOkCancelAlertDialog() as result variable.
