### ISSUE TITLE
Is it supposed to be dismissible?

### ISSUE THREAD

**Issue by atreeon** [mono0926/adaptive_dialog#98]
I have the following

```
                var dialogResult = await showAlertDialog(
                  context: context,
                  message: "Hello",
                  barrierDismissible: true,
                );
```

but when I click outside of the dialog the dialog doesn't close, is that correct behaviour?

**Comment by mono0926** [comment]
@atreeon 

It only works for the Material style, but the documentation lacks that information.
I've added about it now 👌

**Comment by mono0926** [comment]
It just works 🤔 

https://user-images.githubusercontent.com/1255062/214246321-5d8f21a4-154e-4030-b5e4-5db4112c390f.mov
